### ISSUE TITLE
d2rq:lang and d2rq:sqlExpression are not compatible, but d2rq says they are

### ISSUE THREAD

**Issue by gAdrev** [d2rq/d2rq#264]
D2RQ outputs the following error:
d2rq:lang can only be used with d2rq:column, d2rq:pattern or d2rq:sqlExpression at d2rq:PropertyBridge map:catalegtargetes_lit_modalidad_ca (E27)

For the following mapping (stripped irrelevant parts):

    map:catalegtargetes_lit_modalidad_ca a d2rq:PropertyBridge;
      d2rq:belongsToClassMap map:CatalegTargetesProducto;
      d2rq:property cbk:catalegtargetes_lit_modalidad;
      d2rq:sqlExpression "CASE WHEN T1.PROP1 = 'VAL1' THEN 'something' ELSE 'something else'";
      d2rq:lang "ca";
      d2rq:additionalPropertyDefinitionProperty map:HasRangeString;
      d2rq:additionalPropertyDefinitionProperty map:HasSubpropertyDatatype;
      d2rq:additionalPropertyDefinitionProperty map:IsOwlDatatype;
      .

It won't accept sqlExpression along with lang. 
d2rq 0.8.1

**Comment by cygri** [comment]
Good catch, thanks! Fixed in 0c44357abd58f018393a8ff2fa1d5313eb1fc776. You can do a `git clone` and build using Apache Ant.
