### ISSUE TITLE
Is there a way to modularize mapping definitions?

### ISSUE THREAD

**Issue by jerger** [d2rq/d2rq#269]
I use d2rq in order to access a liferay database which works really good :-). Unfortunately liferay has much tables & fields so mapping is quite large (about 20Tlines of mapping definition). Is there any way to modularize mapping information (split in multiple files)?

**Comment by cygri** [comment]
The `generate-mapping` script has `--tables` and `--skip-tables` option that allows export of selected tables. The list of tables can be loaded from a file or specified as a regex. This should allow the creation of more manageable mapping files.

The mapping files themselves are in Turtle syntax, which is an RDF-based syntax, so the usual RDF tools can be used to manage individual files and combine them into one.

**Comment by jerger** [comment]
Export only the selected tables is not the problem. But I want to enrich the exported mapping by hand written parts (comments, additional joins, aso.). Hand written parts are not manageable between other 20T generates lines ...

So I split up into seamtic meaningfully blocks like

```
@prefix map: <#> .
....

# Table Portlet
map:Portlet a d2rq:ClassMap;
    d2rq:dataStorage map:database;
    d2rq:uriPattern "Portlet/@@Portlet.id_@@";
    d2rq:class vocab:Portlet;
    d2rq:classDefinitionLabel "Portlet";
...
```

If I understand right your proposal is to copy all these partial files together into on single file in order to configure d2rq?
As I know no RDF tool for this purpose, I've to do some sed/awk magic for cutting prefixes from all but the first file?

**Comment by cygri** [comment]
In general, Turtle files can be merged simply by concatenating them. The only caveat is that relative URLs will change. Apache Jena's `rdfcat` tool is an option for merging RDF files that works with various syntaxes besides Turtle.

**Comment by jerger** [comment]
works - thanx :-)
