### ISSUE TITLE
Error accessing Sparql Endpoint

### ISSUE THREAD

**Issue by croberto** [d2rq/d2rq#273]
Hi everybody. I need urgent help. Everytime I start the D2R Server with the following line:

d2r-server -p 8080 mapping_file.ttl

It works well. I can enter the link "http://localhost:8080/". But when I try to enter the sparql endpoint at: "http://localhost:8080/sparql" it gives me an error: 

"HTTP ERROR 400 Problem accessing /sparql. Reason: No query string"

Can someone help me? I need to acces the sparql endpoint to try some queries.

Thanks in advance.

**Comment by cygri** [comment]
The SPARQL endpoint at `/sparql` is an API. Use it with a SPARQL client. For a query form where you can enter queries for execution, go to `http://localhost:8080/snorql/`.
