### ISSUE TITLE
Tomcat error when trying to run  D2r server  in Tomcat

### ISSUE THREAD

**Issue by buxg** [d2rq/d2rq#279]
I generated a  D2rq.war in D2rq-0.8.1,  by following the steps described in the D2r-server manual at the 3.2  paragraph (Running D2R Server in a servlet container), and I deployed in the webapps of Tomcat 8.0, but when I try to launch the Tomcat in the web browser (localhost:8080/d2rq) i have a "status report 404 - The requested resource is not available".

Here in the following an extract of the Tomcat log with some details on the error.
Can someone help me to solve the problem?
Thanks Giuseppe Bux.

SEVERE [localhost-startStop-3] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class de.fuberlin.wiwiss.d2rq.server.WebappInitListener
 java.lang.RuntimeException: No configFile configured in web.xml
    at de.fuberlin.wiwiss.d2rq.server.WebappInitListener.contextInitialized(WebappInitListener.java:35)
...........

SEVERE [localhost-startStop-3] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class de.fuberlin.wiwiss.d2rq.server.WebappInitListener
 de.fuberlin.wiwiss.d2rq.D2RQException: no mapping file or JDBC URL specified (E0)

at de.fuberlin.wiwiss.d2rq.SystemLoader.getMappingModel(SystemLoader.java:253)
......

**Comment by cygri** [comment]
The section near the beginning of the `web.xml` file must look something like this:

```
<!-- Configuration file for running the server in a servlet container.
     Will be ignored if the server is started from the command line. -->
<context-param>
  <param-name>configFile</param-name>
  <param-value>my-config-file.ttl</param-value>
</context-param>
```

And then place `my-config-file.ttl` in the `WEB-INF` directory next to the `web.xml` file.

How does that part of your `web.xml` look?

**Comment by buxg** [comment]
Issue resolved!
My error was the replacement of "configFile" parameter with the  my-config-file name without the .ttl extension, as follows:

<context-param>
  <param-name>pgsc</param-name>
  <param-value>pgsc.ttl</param-value>
</context-param>

Thanks for the kind immediate assistance.
Giuseppe Bux

**Comment by cygri** [comment]
Glad I could help!
