### ISSUE TITLE
Tomcat d2rq.war deployment do not generate d2rq/directory branch

### ISSUE THREAD

**Issue by buxg** [d2rq/d2rq#280]
I deployed my pgsc.war  application in Tomcat, so,  when launching on the web browser, the localhost:8080/pgsc display the d2r server home page with on top the clickable  table_names of mymapped pgsc database, as from my pgsc.ttl. However the link underlying each mapped table_name is: 
localhost:8080/directory/table_name ,  

while it should be:
 localhost:8080/pgsc/directory/table_name.

So Tomcat  generates an:  http status 404 - /directory/table_name
with message: The requested resource is not available.

What is missing in the .war deployment procedure?

How to configure tomcat in order to generate the correct  link to the  path localhost:8080/pgsc/directory/table_name ?

**Comment by buxg** [comment]
Issue resolved!

In my pgsc.ttl I refined the baseUri to:

http://localhost:8080/pgsc/

so the  link to the directory branch of the table_names is correctly generated.

Best regards,
G. Bux

**Comment by cygri** [comment]
Thanks for reporting back with the successful resolution!
