### ISSUE TITLE
Building a rdf graph of the db via SNORQL interface

### ISSUE THREAD

**Issue by buxg** [d2rq/d2rq#282]
An important aspect of my project (PGSC project in the context of the FRACTALS FIWARE accelerator program) is to publish the PGSC data  in LOD format. So I would enable the visitors of the PGSC portal (www.pgsc.eu) to build, via SNORQL interface, the current LOD view of the whole PGSC db.
I assume that the CONSTRUCT Sparql query should be used: it should build the whole rdf graph of the db, starting from a root resource and, via join properties linking resources of other tables, traversing all the db and so generating the rdf description of the  whole db . What i mean, definitely,  is to make a dump-rdf, via SNORQL interface.
At moment my trials were unsuccesfull. 
Does this dump building perspective can be achieved?
Giuseppe

**Comment by cygri** [comment]
D2R Server is already LOD compatible. If you can navigate from one resource to another in the D2R Server web interface, then these resources are linked properly in the RDF data. And D2R Server creates not just a web page but also an RDF representation for each resource. You can look at it by clicking the RDF icon in the top right corner of each page.

I don't know why you'd need Snorql or CONSTRUCT for any of this.

If you want to do the same as `dump-rdf` through the SPARQL endpoint, then run this SPARQL query:

```
CONSTRUCT { ?s ?p ?o } WHERE { ?s ?p ?o }
```

This dumps the entire database.

**Comment by buxg** [comment]
It's all OK!
Thank you very much  for your kind support!
Giuseppe Bux

**Comment by cygri** [comment]
You're very welcome!
