### ISSUE TITLE
Sparql query to construct a rdf graph of classes and properties of a d2r repository

### ISSUE THREAD

**Issue by buxg** [d2rq/d2rq#284]
I have a d2r mapping of my database that I can query via the SNORQL web interface. Can you please suggest me a CONSTRUCT SPARQL query to build the rdf graph of  all classes and properties generated by the d2r mapping file?

Thanks in advanca,

Giuseppe

**Comment by buxg** [comment]
Any feedback?
I tried various query solution both with the CONSTRUCT and the SELECT, in order to have a query result displaying  domain and range classes of each property, but without success. I think it could be very useful for a SNORQL endpoint visitor to  have available such a successful query pattern  on the db ontology in order to  be driven in the composition of  subsequent  query patterns  on the db resources.

**Comment by cygri** [comment]
You can use the `-v` option on `generate-mapping` to create an RDFS/OWL vocabulary that matches a default mapping file. If you've customised your mapping, you need to modify/create your vocabulary yourself.

**Comment by buxg** [comment]
Please  could you provide me with examples  of vocabulary customization?
Here below a default mapping and  related rdfs/Owl mapping of a class and a property:

```
    map:farm a d2rq:ClassMap;
d2rq:dataStorage map:database;
d2rq:uriPattern "farm/@@farm.Id@@";
d2rq:class pgsc:farm;
d2rq:classDefinitionLabel "farm";
.
```

  :farm
      a       owl:Class , rdfs:Class ;
      rdfs:isDefinedBy : ;
      rdfs:label "farm" .

 map:farm_CodFiscaleRapprLeg a d2rq:PropertyBridge;
    d2rq:belongsToClassMap map:farm;
    d2rq:property pgsc:farm_CodFiscaleRapprLeg;
    d2rq:propertyDefinitionLabel "farm CodFiscaleRapprLeg";
    d2rq:column "farm.CodFiscaleRapprLeg";.

 :farm_CodFiscaleRapprLeg
      a       owl:DatatypeProperty , rdf:Property ;
      rdfs:domain :farm ;
      rdfs:isDefinedBy : ;
      rdfs:label "farm_CodFiscaleRapprLeg" ;
      rdfs:range xsd:string;
      .

```
.
```

**Comment by buxg** [comment]
Because of my long db mapping.ttl file, an hand made modification of its vocabulary, with the rdfs/owl vocabulary, appears as  a very time-consuming and error-prone work.  So I prefer to maintain the original mapping file. I tried  the --w3c option to generate the db mapping.ttl file, but it seems that the result do not change. It could be very useful that the --w3c option directly generate a w3c compliant RDFS/OWL db mapping. 
Again thanks for your kind assistance.
Giuseppe Bux
