### ISSUE TITLE
how to config many to many ?

### ISSUE THREAD

**Issue by AniaDavid** [d2rq/d2rq#286]
I have a database tables and I'm changing the data to RDF.

So far I am able to do the one to one in which a row that has a primary key, has a value, which comes from a column in that row, like this:

```
map:Artist a d2rq:ClassMap;
    d2rq:dataStorage map:database;
    d2rq:class to:Artist;
    d2rq:uriPattern "to:Artist/@@M3.ARTIST.ARTIST_ID@@";
    .

map:ArtistName a d2rq:PropertyBridge;
    d2rq:belongsToClassMap map:Artist;
    d2rq:property to:hasName;
    d2rq:column "M3.ARTIST.ARTIST_NAME";
    d2rq:datatype xsd:string;
```

```
.
```

here each Artist_ID will be the subject of the triple and there will be a property called hasName with its value comes from the ARTIST_NAME column

so far so good, now i have a table many to many like this:

Artist(table) Album(Table) ArtistAlbum(table)

the artistalbum has a foriegn key to both of Album and Artist

how can I do that in r2rq please?

**Comment by cygri** [comment]
See here for an example that connects instances from two tables (but it's one to many, not many-to-many):
http://d2rq.org/d2rq-language#example-refers

See here for an example that takes a property from a different table, and the table is joined via a many-to-many relationship table:
http://d2rq.org/d2rq-language#example-join

Combine the two examples to address your scenario.

Feel free to re-open the issue if you need more help.
