### ISSUE TITLE
R2RML support in latest branch

### ISSUE THREAD

**Issue by JensPiegsa** [d2rq/d2rq#287]
It looks like the [develop](https://github.com/d2rq/d2rq/tree/develop) branch (Latest commit on 28 Aug 2014) has R2RML support, but [d2rq2016](https://github.com/d2rq/d2rq/tree/d2rq2016) (Latest commit on 15 Feb 2016) has not.

Since this feature is crucial for our project, any additional information about this would be very welcome.

**Comment by cygri** [comment]
It's quite a mess!

The develop branch contains an unfinished implementation of R2RML support. Things that work: generate-mapping, dump-rdf, validate. However, the SPARQL engine for R2RML is unfinished. It will produce correct results, but the necessary optimisations for reasonable performance are not implemented. So SPARQL queries will often be _very very_ slow.

Ignore d2rq2016, it was an attempt to start sorting out the situation but didn't go anywhere useful yet.

**Comment by JensPiegsa** [comment]
Thanks for your quick reply and the clarification.
