### ISSUE TITLE
how to include only prefix in the generated instances

### ISSUE THREAD

**Issue by AniaDavid** [d2rq/d2rq#288]
This is the full question on Stckoverflow 

https://stackoverflow.com/questions/37140449/rdf-change-the-format-to-include-prefix

Bacialy, I want the generated triples to have this formation
`prefix:primaryKey`

so I dont want to have the greater and smaller sign at the begining and end of the uri

I am not able to, could you hep please ?

**Comment by cygri** [comment]
Answer posted on SO
