### ISSUE TITLE
Retrieving html/rdf documents by appending the file extension to a resource's URL

### ISSUE THREAD

**Issue by pasean** [d2rq/d2rq#294]
Hi Richard,

we would like to set up an RDF interface for our lithological dictionary database using d2r-server. One of our requirements will be that if someone appends ".html" or ".rdf" to a resource's URL, he would obtain the correspondingly formatted documents. Could you possibly give us a hint on how to add this functionality to your code most easily?

Best regards,

Andreas

**Comment by cygri** [comment]
Have a look at `webapp/WEB-INF/web.xml` and how it maps the paths such as `/resource/*`, `/page/*` and `/data/*` to the various servlets. Servlet mappings in `web.xml` cannot be done based on extension but only on the initial part of the URL, so you'll need a single servlet that dispatches to the right code path depending on the extension. I suppose you could modify `ResourceServlet.java` to dispatch to `PageServlet.java` if there's a `.html` extension, etc.

**Comment by pasean** [comment]
Thank you for your help, Richard. 

We will try our luck.

Best regards,

Andreas
