### ISSUE TITLE
Possible to create SPARQL relationship to D2RQ object?

### ISSUE THREAD

**Issue by BPMNhero** [d2rq/d2rq#303]
I have been struggling to create a SPARQL to D2RQ exposed SQL db element triple with no success. Is this possible to create a triple on a SPARQL server that points to an instance of data through
 a R2DQ server? 
I understand that columns are represented as predicates and rows as objects. 
I want to create a SPARQL subject that refers to a R2DQ exposed data instance, so I can query through that reference in the SPARQL world and traverse the SQL data. Is this possible? Am I missing something simple?
I will provide a graphic to help illustrate.
[D2RQ reference.pptx](https://github.com/d2rq/d2rq/files/1192467/D2RQ.reference.pptx)

**Comment by cygri** [comment]
I have a bit of trouble understanding the request.

You have some data in a SQL database? Have you got D2R Server up and running on top of that database with an auto-generated mapping file? That should give you an idea about the way D2RQ maps the relational data to triples. The same triples that you can visually browse and navigate in D2R Server are also accessible through a SPARQL endpoint.

**Comment by BPMNhero** [comment]
Yes, I have a D2R server running and exposing a small SQL db through an autogenerated  .ttl mapping file. I can view SQL data through the D2R web page at port 2020.
I can query the D2R from a SPARQL server just fine using SERVICE.

It is just about the mechanics to link an object in a SPARQL server to the D2R exposed object.
I have tried to INSERT:
?local_SPARQL_obj rdfs:isDefinedBy ?D2R_obj .
with no success. 
My goal is to add an object into the SPARQL side that I can control to create a reference to the D2R data that I can't change. This is why I think the rdfs:isDefinedBy predicate is proper.

It sounds like this should be easy, yet something eludes me. 
Any suggestions are welcome.
MR

**Comment by cygri** [comment]
Okay, so you have some data in a triple store, and then more data about the same entities exposed through D2RQ. And you can query them both together by querying the triple store and using SERVICE to get at the data in D2RQ.

Now it looks like you're trying to add some triples to the triple store that connect the data from both sides, on the level of individual resources. Creating a “reference” between them, as you say.

What is the goal of adding these references? Do you just want a reference for the sake of having a reference, or do you expect it to change the data that is returned by queries?

In what way did the INSERT that you tried not succeed? Did it not create the desired triples, or were triples added but they didn't have the desired effect?

**Comment by BPMNhero** [comment]
The goal of the reference is to locally (SPARQL side) align that reference with other local business objects while also having access to the SQL data, which has operational configuration information for services and operations. I wish to query across both sides of the data to produce reports.

E.g. my reference node would be a unique service name that has a local SPARQL relationship with the business capabilities it supports. 
The reference node would have an additional relationship to the D2R object that contains operational information about that service (version, consumers, etc.). This is what confounds me ***
I would like to solely query on the SPARQL side, accessing data on my business capabilities AND access the D2R side of operationally relevant information. I do not want to change anything on the D2R side, just read it through that reference.

Upon a SERVICE query to the D2R side I do: 
?s <http://xxx.com:2020//resource/vocab/OPERATION_NAME> ?op_name .
This gives me output:
op_name                                    s
"addSourceId" 	                400000001
"administerCaseEvaluation" 	400000002
Where the subject is the SQL table index number (a unique value), the op_name is the row data for that column which is an operation name.
My inserts are failing to produce a triple. 
An interesting point is that the following query returns no data:
"400000001" <http://xxx.com:2020//resource/vocab/OPERATION_NAME> ?op_name .
But this next query does return data:
?s <http://xxx.com:2020//resource/vocab/OPERATION_NAME> "addSourceId" .
Returns:
s
400000001

I am concerned that it is not possible to create the reference I see on the SQL index reflected through D2R as this little experiment may indicate. Is it not possible to fix a subject in such a D2R mapping?

I was hoping it is possible to have my reference point to the subject (400000001, the index of SQL table) to have a unique "pointer" into one record of the SQL table from SPARQL. Maybe I am treating this too much like C programming, but it seems to be possible., butI may be missing something fundamental.
Thanks again for any insight.

**Comment by tayloj** [comment]
> My inserts are failing to produce a triple.
> An interesting point is that the following query returns no data:
> "400000001" http://xxx.com:2020//resource/vocab/OPERATION_NAME ?op_name .
> But this next query does return data:
> ?s http://xxx.com:2020//resource/vocab/OPERATION_NAME "addSourceId" .
> Returns:
> s
> 400000001

The subject of a triple in RDF can only be an IRI or a blank node. The
subject cannot be a literal (such as a string).  So

    "400000001" <http://xxx.com:2020//resource/vocab/OPERATION_NAME> ?op_name .

is a legal pattern in SPARQL (I think), but can't actually match any
triple, because no triple can have that subject.  Now, given that you
say that:

    ?s http://xxx.com:2020//resource/vocab/OPERATION_NAME "addSourceId" .

returns results, I think that the presentation must be showing you
"400000001" as a shorthand for some IRI. It could be something where a
prefix has been defined (e.g., <http://example.org/400000001>), or
maybe there's a bug in your DB to triple mapping wherein literals are
somehow allowed to be in subject position (but that would be
surprising, and isn't legal in RDF).

**Comment by BPMNhero** [comment]
Yes: 
"I think that the presentation must be showing you
"400000001" as a shorthand for some IRI."

That is true, the fully qualified IRI is:
<http://xxx.com:2020/resource/db/SERVICE_OPERATION_MASTER/400000001>
Thanks for the hint.
MR

**Comment by BPMNhero** [comment]
Thank you for your supporting comments! I have the solution. It was as tayloj  said, the subject URI must be obscured by the server. My solution was to use URI() to cast into a proper URI, then I was able to create these relationships (no wonder my server rejected it). Now that I have such a cross db relationship I just need a cross db query and I will be set... on to my next step. I will respond once I get that in-case it can help someone else.
Thanks!
MR

**Comment by cygri** [comment]
@BPMNhero, glad you were able to figure it out! And thanks @tayloj for jumping in with the critical bit of information.

I'll close this ticket for now, but please feel free to comment further or re-open as you see fit.
