### ISSUE TITLE
Please Help dump-rdf taking very long

### ISSUE THREAD

**Issue by damilolah** [d2rq/d2rq#304]
Hello,

I'm trying to convert my_dataset.sql to .ttl TURTLE format.

I did the following:

./generate-mapping -o gendata100.ttl -u user -p passwd jdbc:mysql://localhost/my_dataset

./d2r-server gendata100.ttl

I was able to see my tables on the browser at http://localhost:2020/ 

I now ran this:

./dump-rdf -f TURTLE -b http://localhost:2020/ gendata100.ttl > final_data.ttl

I can see a final_data.ttl file in my d2rq-0.8.1 folder but it is 0 bytes. 

I've be running this:
./dump-rdf -f TURTLE -b http://localhost:2020/ gendata100.ttl > final_data.ttl 

for the past 10 hours and it has remained that way, no change, no error and final_data.ttl  did not increase in size.

my_dataset.sql file is about 85MB and gendata100.ttl is about 321.1KB PLEASE HELP

What am I doing wrong?

**Comment by cygri** [comment]
Did you try without `-f TURTLE`?

**Comment by cygri** [comment]
To expand a bit on that comment: The default output format (N-Triples) streams the output to file. But Turtle output in current D2RQ doesn't—it requires pulling all data into memory first. If your SQL file is 85MB, then the resulting RDF data could well be a gigabyte or more. By default, `dump-rdf` is limited to using 1G of memory. As usual with Java applications, if the used memory gets close to the limit, the application will slow to a crawl before eventually running out of memory. This is consistent with what you described—nothing happening for a very long time.

Note that N-Triples is a subset of Turtle, so every N-Triple file is in fact a valid (albeit very verbose) Turtle file.

Some other things you could try:

- Edit the `dump-rdf` script and change `-Xmx1G` to, say, `-Xmx10G` if your machine has more than 10G of memory available
- Run with `--verbose -o final_data.ttl` to get more detailed output

**Comment by damilolah** [comment]
Thanks so much. My file was so large. I was able to generate the file on a system with more memory.
