### ISSUE TITLE
generate-mapping... Unknown argument: -b

### ISSUE THREAD

**Issue by damilolah** [d2rq/d2rq#305]
Hi!

I'm trying to generate mappings following this tutorial:
http://d2rq.org/generate-mapping. I am specifying my base URI but it doesn't recognize the option -b.

./generate-mapping -u root -p pass -o output.ttl  -b http://mybaseURI/ jdbc:mysql://localhost/my_DB

**Comment by cygri** [comment]
See #221. Closing as duplicate.
