### ISSUE TITLE
Error when querying. strange select command: `Incorrect syntax near '='

### ISSUE THREAD

**Issue by wisamx** [d2rq/d2rq#306]
I try to run the query

```
SELECT DISTINCT * WHERE {
?x ?y <http://localhost:1111/resource/organization/1>.
}
```

then i get this strange sql select statement error.

`Incorrect syntax near '='.: SELECT "dbo"."Degrees"."Subject" = 'http://localhost:1111/resource/organization/1' AS exprbbe168c0, "dbo"."Degrees"."SameAsURI" = 'http://localhost:1111/resource/organization/1' AS exprbbe168c0, "dbo"."Degrees"."Id" FROM "dbo"."Degrees" WHERE (("dbo"."Degrees"."SameAsURI" = 'http://localhost:1111/resource/organization/1' AND "dbo"."Degrees"."SameAsURI" IS NOT NULL) OR ("dbo"."Degrees"."Subject" = 'http://localhost:1111/resource/organization/1' AND "dbo"."Degrees"."Subject" IS NOT NULL)) (E0)`

what is the problem!?

**Comment by cygri** [comment]
- What Version of D2RQ is this?
- What database, and what version of the database?
- Do you have a way of running the shown SQL query directly against the database? If so, what happens?

**Comment by wisamx** [comment]
D2RQ 0.8.1
Microsoft SQL Server Express (64-bit) v11.0.3000.0
When trying to run the sql command directly on sql server i get the same error.
actually, as I know there no rule like
`SELECT "dbo"."Degrees"."Subject" = 'http://localhost:1111/resource/organization/1' AS exprbbe168c0,`
Is should be `SELECT "dbo"."Degrees"."Subject" AS exprbbe168c0,`

just to know I have such a property bridge

```
map:deg8 a d2rq:PropertyBridge;
	d2rq:belongsToClassMap map:Degrees;
	d2rq:property dc:subject;
	d2rq:propertyDefinitionLabel "Subject";
	d2rq:uriColumn "dbo.Degrees.Subject";
	.
```

**Comment by cygri** [comment]
Seems to [same issue as this](https://stackoverflow.com/questions/7778444/sql-select-return-boolean-based-on-condition). Basically, SQL Server doesn't have a Boolean datatype, so it can't return the result of a boolean expression in the `SELECT` list.

**Comment by wisamx** [comment]
is there any solution to make it work for the d2rq platform with sql server (any version).
or is there any easy patch to the d2r server, I can use.
cause I can't change my database server.

**Comment by cygri** [comment]
I can't think of any way to make that work with the current release of D2RQ. Avoiding SPARQL queries with variable predicates might help.

**Comment by wisamx** [comment]
now I know that to solve my problem, d2rq need to use the case expression, so instead of

"dbo"."Degrees"."Subject" = 'http://localhost:1111/resource/organization/1' AS exprbbe168c0

It must use

CASE WHEN "dbo"."Degrees"."Subject" = 'http://localhost:1111/resource/organization/1' THEN 1 WHEN "dbo"."Degrees"."Subject" <> 'http://localhost:1111/resource/organization/1' THEN 0 END AS exprbbe168c0

now I have to hook into d2rq and change the way how select statements are generated.
is there any guidance or development documents I can use to learn how to do that.

Thank you for the help

**Comment by cygri** [comment]
I think the last few comments on #154 may discuss the same problem as this one, and one commenter proposed a fix there.

**Comment by wisamx** [comment]
I did the edits to src\de\fuberlin\wiwiss\d2rq\sql\vendor\SQL92.java and src\de\fuberlin\wiwiss\d2rq\sql\vendor\SQLServer.java
and run the d2r-server.bat
but It seems I miss something like do some compile or clear some cache.
cause i still get the same error message!

**Comment by cygri** [comment]
Instructions for building from source are at https://github.com/d2rq/d2rq

If you don't have some Java development experience already, then you might find this a bit of an uphill battle.

**Comment by wisamx** [comment]
I did the changes, compiled the source code.
and It just worked.
Thanks

**Comment by cygri** [comment]
Nice job, and good to know!
