### ISSUE TITLE
Incorrect Turtle file with missing mapping

### ISSUE THREAD

**Issue by priya-gitTest** [d2rq/d2rq#311]
Hi, 

I try to generate the TURTLE file, but some of the Fields of the DB are not getting resolved correctly.
dump-rdf -o turtle_data.ttl -f TURTLE --debug data_mapping.ttl
Mapping is defined in the data_mapping.ttl file. I dont see any errors, just that the data is not in right hierarchy for some fields only. 
Has anyone faced similar issues ?

Correct Mapping for City resolution, ooo:O8701  is a subclass of ooo:O883 
```
<file:///C:/d2rq-0.8.1/turtle_data.ttl#office/315>
      a       Office;
     ooo:O00025 <file:///C:/d2rq-0.8.1/turtle_data.ttl#City/315> ;
      ooo:O00251 <file:///C:/d2rq-0.8.1/turtle_data.ttl#DateofOpening/315> .

<file:///C:/d2rq-0.8.1/turtle_data.ttl#City/315>
      a       ooo:O8701 , ooo:O883 .
```
Incorrect Mapping resolution in turtle_data.ttl 
```
<file:///C:/d2rq-0.8.1/turtle_data.ttl#office/9711>
      a       Office;
      ooo:O00025 <file:///C:/d2rq-0.8.1/turtle_data.ttl#City/9711> ;
      ooo:O00251<file:///C:/d2rq-0.8.1/turtle_data.ttl#DateofOpening/9711> .

<file:///C:/d2rq-0.8.1/turtle_data.ttl#City/9711>
      a       ooo:O883  .
```
Database has data for city for  both offices

**Comment by cygri** [comment]
I edited your comment so that the Turtle shows correctly.

Please provide some details about the relevant part of the database schema and the relevant part of the D2RQ mapping. Also, what triples are unexpected/missing? It's hard to tell the problem from just seeing the output but not the input or the mapping.

**Comment by priya-gitTest** [comment]
Hi, the issue is resolved. You can close or delete this request.  The issue was some space in the DB columns, hence the mapping was not generated correctly. Reomving the spaces did the Trick.
