### ISSUE TITLE
mapping a class and its subclasses from an entity table and attributes 

### ISSUE THREAD

**Issue by MarcyRouge** [d2rq/d2rq#328]
Hello, 

I have some questions concerning the mapping of a class and subclasses with the instances of the subclasses. To this end, I have made up a simple example to illustrate my questions with the hope of being helped. 
Thanks in advance 

**CONTEXT**

Let’s say I have a table “Person” composed of 4 attributes: Id, name, age, typology

In the attribute typology I have : Child, Adult and Elderly 

These three attributes are the subclasses of the class person in my ontology: 

Person 
   Child
   Adult
   Elderly

The instances from the table should populate my subclasses and not the class mother ‘Person’.

**STEPS AND QUESTIONS:**

Therefore there are three steps that I want to do which takes me to my two questions: 

1.	Create a class Person but with no instances from the table. **Question – How to do that if I am forced to use a column or and uri when creating the class map. Is there a way to refer to the classes created below?** 

2.	Map the attribute Person.name to the corresponding class (child, adult, elderly ). This part is solved as you can see below

3.	Define the three classes (child, adult, elderly) as subclasses of the class Person. **Question – how can I do that?** 
	

**MAPPING:** 

1.

# Table dbo.Person
#class Person
map:dbo_Person a d2rq:ClassMap;
	d2rq:dataStorage map:database;
	**d2rq:uriPattern ????**
	d2rq:class OntoPopulation :Person;

2. 

# Table dbo_Child -  This table does not exist in the database, but it is created as it exists as class in the ontology 
map:dbo_child a d2rq:ClassMap;
	d2rq:dataStorage map:database;
	d2rq:uriPattern "http://www.semanticweb.org/Population -inst#@@dbo.person.Name@@";
	d2rq:condition "dbo. person.Typology = 'Child'";
	d2rq:class OntoPopulation:Child;
	.
	

# Table dbo_adult -  This table does not exist in the database, but it is created as it exists as class in the ontology 	
#class OntoPopulation:Adult
map:dbo_Adult a d2rq:ClassMap;
	d2rq:dataStorage map:database;
	d2rq:uriPattern "http://www.semanticweb.org/Population -inst#@@dbo.person.Name@@";@@";
	d2rq:condition "dbo. person.Typology = 'Adult'";
	d2rq:class OntoPopulation:Adult;
	.
	

# Table dbo_Elderly -  This table does not exist in the database, but it is created as it exists as class in the ontology 
#class OntoPopulation:Elderly
map:dbo_Elementary a d2rq:ClassMap;
	d2rq:dataStorage map:database;
	d2rq:uriPattern "http://www.semanticweb.org/Population -inst#@@dbo.person.Name@@";@@";
	d2rq:condition "dbo.person.Typology = ‘Elderly’ ";
	d2rq:class OntoPopulation: Elderly;

3.

 I used d2rq:additionalClassDefinitionProperty as in the exemple but it doesn't work. Nothing is displayed when I query 

SELECT ?person WHERE {
   OntoPopulation:Child rdfs:subClassOf ?person
}
  
map:dbo_child a d2rq:ClassMap;
d2rq:dataStorage map:database;
d2rq:uriPattern "http://www.semanticweb.org/Population -inst#@@dbo.person.Name@@";
d2rq:condition "dbo. person.Typology = 'Child'";
d2rq:class OntoPopulation:Child;
**d2rq:additionalClassDefinitionProperty map:ChildSubClassOf;**
.

map:ChildSubClassOf a d2rq:AdditionalProperty;
	d2rq:propertyName rdfs:subClassOf;
	d2rq:propertyValue OntoPopulation:Person;

**Comment by MarcyRouge** [comment]
ps: for the point 3

 I used d2rq:additionalClassDefinitionProperty as in the exemple but it doesn't work. Nothing is displayed when I query 

SELECT ?person WHERE {
   OntoPopulation:Child rdfs:subClassOf ?person
}
  
map:dbo_child a d2rq:ClassMap;
d2rq:dataStorage map:database;
d2rq:uriPattern "http://www.semanticweb.org/Population -inst#@@dbo.person.Name@@";
d2rq:condition "dbo. person.Typology = 'Child'";
d2rq:class OntoPopulation:Child;
**d2rq:additionalClassDefinitionProperty map:ChildSubClassOf;**
.

map:ChildSubClassOf a d2rq:AdditionalProperty;
	d2rq:propertyName rdfs:subClassOf;
	d2rq:propertyValue OntoPopulation:Person;

**Comment by cygri** [comment]
This scenario is addressed here: [Example: A group of classes all mapped from the same table](http://d2rq.org/d2rq-language#example-dynamic-type)

The key concept to understand here is that in RDF, “this instance is a member of that class” is just another property of the instance, with the predicate `rdf:type`. Usually, the `rdf:type` for the instances generated by a class map are all the same—the value of `d2rq:class`. But there's nothing stopping you from removing `d2rq:class` and using a property bridge with `d2rq:property rdf:type` that produces the URIs of the desired subclasses.

So you just need a single classmap with a dynamically generated `rdf:type` value, rather than three classmaps that filter the same table with `d2rq:condition`.

Again, please feel free to reopen the ticket if this doesn't solve your issue.
